// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dbggosyqxhyydaypdhny.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRiZ2dvc3lxeGh5eWRheXBkaG55Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5NDIwNTAsImV4cCI6MjA2MzUxODA1MH0.94gRITL4FkBceDx_7it82GNLxhm4r0YtOLx9J5ywZ3w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);